
POST http://localhost:8080/agent/c/create-real-estate-for-sale HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjIiwicm9sZXMiOlsiUk9MRV9BR0VOVCJdLCJleHAiOjE3NDUzNjUyNjEsImlhdCI6MTc0NTI3ODg2MX0.Dwk1jOVON1XIcbCF2IUinEYuDDT_BoV5ao6GAea6jUc
Content-Type: application/json 

{
    "estateDescribe" :
        {
            "title" : "a",
            "description" : "a",
            "price" : 500,
            "condoFee" : 10,
            "energyClass" : "b",
            "size" : 50,
            "roomsNumber" : 4,
            "estateCondition" : "aa",
            "furnitureCondition" : "aa",
            "parkingSpacesNumber" : 5,
            "floorNumber" : 3
        },
    "estateFeatures" :
        {
            "hasAirConditioning" : false,
            "hasHeating" : true , 
            "hasElevator" : true,
            "hasConcierge" : false,
            "hasTerrace" : false,
            "hasGarage" : false,
            "hasBalcony" : true,
            "hasGarden" : false,
            "hasSwimmingPool" : false
        },
    "estateLocationFeatures" :
        {
            "nearPark" : true,
            "nearSchool" : true,
            "nearPublicTransport" : true
        },
    "address" : 
        {
            "state" : "aaa",
            "country" : "aaa",
            "city" : "aaa",
            "street" : "aaaa",
            "postalCode" : "aaaa",
            "houseNumber" : 44,
            "latitude" : 4.9,
            "longitude" : 2
        },
    "notaryDeedState" : "aaaaa"
}

GET http://localhost:8080/agent/c/recent-real-estates/1 HTTP/1.1
Authorization: Bearer 


GET http://localhost:8080/real-estate/search3?page=0&limit=3&type=For%20Sale&lat=4.9&lon=2&radius=1000000 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjIiwicm9sZXMiOlsiUk9MRV9BR0VOVCJdLCJleHAiOjE3NDUzNjUyNjEsImlhdCI6MTc0NTI3ODg2MX0.Dwk1jOVON1XIcbCF2IUinEYuDDT_BoV5ao6GAea6jUc


GET http://localhost:8080/real-estate/search4?page=0&limit=3&type=For%20Sale&lat=4&lon=2&radius=10000hasBbalcony=true HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjIiwicm9sZXMiOlsiUk9MRV9BR0VOVCJdLCJleHAiOjE3NDE5ODI3MDQsImlhdCI6MTc0MDI3NzY3MX0.venEMjKR1d8bWHl6Sxcj2i_H50NJNZmIjgU7oX-uyMc


GET http://localhost:8080/agent/c/agent-stats HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjIiwicm9sZXMiOlsiUk9MRV9BR0VOVCJdLCJleHAiOjE3NDIyMTE0NTMsImlhdCI6MTc0MDUwNjQyMH0.YIyL4hdt3QGx8eVa5iCcGSJQm4IoVWPOEdjAIfH--Vg


GET http://localhost:8080/agent/c/real-estates-stats/0/2 HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjIiwicm9sZXMiOlsiUk9MRV9BR0VOVCJdLCJleHAiOjE3NDIyMTE0NTMsImlhdCI6MTc0MDUwNjQyMH0.YIyL4hdt3QGx8eVa5iCcGSJQm4IoVWPOEdjAIfH--Vg


GET http://localhost:8080/agent/c/general-stats HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjIiwicm9sZXMiOlsiUk9MRV9BR0VOVCJdLCJleHAiOjE3NDIyMTE0NTMsImlhdCI6MTc0MDUwNjQyMH0.YIyL4hdt3QGx8eVa5iCcGSJQm4IoVWPOEdjAIfH--Vg