
POST http://localhost:8080/auth/standard-registration HTTP/1.1
Content-Type: application/json

{
    "name" : "adfsdfsdf",
    "surname" : "dssdf",
    "username" : "aaahaaaaaa@gmail.com",
    "password" : "adsfadsfadA0?0s"
}


POST http://localhost:8080/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=c&password=ssssssssssssssssssss22A@&role=agent


POST http://localhost:8080/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=ydk&password=jssssssssssssssssssss22A@&role=admin


GET http://localhost:8080/CSV/c/export HTTP/1.1


GET http://localhost:8080/PDF/c/export HTTP/1.1